package com.tylerdev.lekkerweather.data.remote

import retrofit2.http.GET
import retrofit2.http.Query

/**
 * Retrofit contract for the remote weather service.
 *
 * Declares the HTTP endpoint used to fetch hourly forecast data for a given location. Implementations
 * are generated by Retrofit at runtime; repositories call [getWeatherData] and map the returned
 * [WeatherDto] into domain models.
 */
interface WeatherApi {

    /**
     * Fetches hourly forecast data for the coordinates supplied.
     *
     * @param lat Latitude of the location.
     * @param long Longitude of the location.
     * @return Deserialised forecast payload for the requested point.
     */
    @GET("v1/forecast?hourly=temperature_2m,weather_code,relative_humidity_2m,wind_speed_10m,pressure_msl&timezone=auto")
    suspend fun getWeatherData(
        @Query("latitude") lat: Double,
        @Query("longitude") long: Double
    ) : WeatherDto
}